# .coderabbit.yaml
reviews:
  path_filters:
    # Use "! " at the start of a pattern to EXCLUDE it from the review
    - "!**/doc/**"                # Ignore all generated TypeDoc folders
    - "!**/docs/**"               # Ignore all generated VitePress folders
    - "!**/.vitepress/cache/**"    # Ignore VitePress cache
    - "!**/.vitepress/dist/**"     # Ignore VitePress build output
    - "!**/vendor/**"             # Ignore third-party code
